name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a testing step"

  integration:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  aritifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello /opt/hello.txt
     
      - uses: actions/upload-artificat@v3
        with: 
	  name: my-artificat
	  path: /opt/hello.txt
  
  prod:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"
